### ISSUE TITLE
Patterns / Progress tracker - spacing, design and text edits

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Services/California-State-Web-Template-Website#988]
[Patterns / Progress tracker](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/patterns/progress-tracker.html)

- [ ] Spacing issues in mobile form factor...
![Screen Shot 2022-12-13 at 2 06 02 PM](https://user-images.githubusercontent.com/98193284/207454152-1a7bba88-cf14-40ca-8ae2-1cff77099ae9.png)
![Screen Shot 2022-12-13 at 2 06 14 PM](https://user-images.githubusercontent.com/98193284/207454188-02e418a6-d052-4567-8eb2-073a1bf17c06.png)
---------------

- [x] Vertical tracker - can we use diff text (yy-yy)? maybe numbers? (cc @artuoma)
![Screen Shot 2022-12-13 at 2 06 50 PM](https://user-images.githubusercontent.com/98193284/207454288-3443bdb0-5a7e-42d8-8328-7f16218b31fb.png)
-----------------

- [x] Fix Step list H3’s by removing <strong> that causes to display with an extra bold font. Should display like [Figma](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=564%3A8933&t=D73jc5PQPitRtYfs-1):
![Screen Shot 2022-12-13 at 2 07 27 PM](https://user-images.githubusercontent.com/98193284/207454378-0827375e-d9ac-45c9-8d2f-f9e861fc67d5.png)

-------------

- [x] Fix periods after bullets: Add periods at the end of these bullets like in the Google doc and Figma. 

> Each time a new component version is published:
> * Test with the [axe accessibility tool](https://www.deque.com/axe/).
> * Review with the [VoiceOver](https://www.apple.com/voiceover/info/guide/_1121.html) or [NVDA](https://www.nvaccess.org/download/) screen reader.
> * Ensure all actionable elements are accessible by keyboard command and tab in a logical order. 
> * Check the component layout on a variety of screen sizes.

**Comment by jon-grant-state-ca-gov** [comment]
Regarding adding the periods for Task 4:
In the comments of [Pull request #1037](https://github.com/Office-of-Digital-Services/California-State-Web-Template-Website/pull/1037), there were notes from @kkoryaka and @ashleydraper about not adding in the periods at this time, and adding a colon to color.html

**Comment by extinah** [comment]
@yesenia-gtz  do you remember who provided most of the feedback?

**Comment by yesenia-gtz** [comment]
@extinah  this was from @artuoma

**Comment by extinah** [comment]
@yesenia-gtz  
Task 1: not completed. I recommend the mobile items be created as a backlog item and put in a subsequent release (6.1.1). We need to create mobile designs for all pages. We have a few already in the backlog specifically for mobile that are for the 6.1.1 release:

- Mobile navigation #847 
- On this page mobile view design #854
- Side nav mobile view design #853 

Task 2: @jon-grant-state-ca-gov can you replace "YY - YY" with "Month and year"

**Comment by extinah** [comment]
Reviewed - looks good. Thanks.
